### ISSUE TITLE
Version 5.0 Elasticsearch supported?

### ISSUE THREAD

**Issue by josecolella** [Dynatrace/Dynatrace-AppMon-UEM-PureLytics-Heatmap#2]
Hello,
Would it be possible to document which versions of elastic search are supported? I have a client running version 5.0, and want to understand if the version is supported by the plugin, or if we need to run it with another version

**Comment by HokiCho** [comment]
5.0 supported. 
The filtered query is replaced by the bool query.

**Comment by josecolella** [comment]
Thanks for the answer. @wbytebier, here is your response.
