### ISSUE TITLE
Heatmap not drawn for the complete page

### ISSUE THREAD

**Issue by wbytebier** [Dynatrace/Dynatrace-AppMon-UEM-PureLytics-Heatmap#3]
Hi,
Is it normal that the heat map is not drawn for the whole page?
If I run the script, only the top of the page (on screen) is used to draw the heat map. Even scrolling down an then re-running the script does not draw the heatmap on that part of the screen. The only time the map is drawn completely is when I zoom out the page.

Gr.,
Wilfried

**Comment by wbytebier** [comment]
$("body").append("<div id='heatmap-container' style='display:none;position:absolute;left:0;top:0;width:" + Math.max($(document).width(), $(window).width()) + "px;height:" + Math.max($(document).height(), $(window).height()) + "px;z-index:10000000'></div>");

Gr.,
Wilfried

**Comment by dominikp** [comment]
Hi Wilfried,

thanks for fixing that :-)

I used a workaround for that problem before... simply zoom out until the whole page is visible. Then I use Fireshot to create a screenshot of the page which gives you the full resolution.

But obviously your fix is better!

Dominik

**Comment by dominikp** [comment]
fixed by wbytebier
